// AUTO-GENERATED by scripts/export-seed.ts on 2026-06-10T22:00:33.595Z
// Snapshot of the dev database used as seed data.
// Regenerate after changing data in the DB with:  npm run seed:export
// Then re-seed with:  npm run seed

const sampleData = {
  "users": [
    {
      "name": "adminUser",
      "email": "craig@yoyozi.com",
      "password": "$2a$10$QdimXuKon0M590NiKiiUn.WAoSBflcQByZnz1N64xTk5IblwdsTMe",
      "role": "admin"
    },
    {
      "name": "userUser",
      "email": "craig@netsecurity.co.za",
      "password": "$2a$10$SNTAoaC9QYvE0yE3VDNID.mWK2l9AGuh99DzZ.oPPKSKNNsl8MMYC",
      "role": "user"
    },
    {
      "name": "Charles Chitokoko",
      "email": "charles@streetcraft.co.za",
      "password": "$2a$10$yDJ56ui1/pXa6WM/MAOVdeoV4fXLgGmL1gbUWBgTsxBNf6BVBpSUm",
      "role": "craft"
    }
  ],
  "categories": [
    {
      "name": "Beadwork",
      "description": "Items made using wire and beads",
      "isActive": true
    },
    {
      "name": "Material",
      "description": "Items sewed and stitched out of cloth",
      "isActive": true
    },
    {
      "name": "Paintings",
      "description": "Paintings from selected artists",
      "isActive": true
    }
  ],
  "crafters": [
    {
      "userEmail": "charles@streetcraft.co.za",
      "businessName": "Charles Chitokoko",
      "description": null,
      "location": "Emmerentia",
      "mobile": "+27 21 555 0123",
      "category": null,
      "whatsappNumber": null,
      "city": null,
      "province": null,
      "profileImage": "/images/crafters/active-oxygen-crafts.jpg",
      "workSamples": [],
      "status": "APPROVED",
      "identityVerified": false,
      "isActive": true
    }
  ],
  "products": [
    {
      "name": "Bee flying",
      "slug": "bee-flying",
      "category": "Beadwork",
      "description": "A flying bee",
      "images": [
        "https://utfs.io/f/LQrirZFCBqET6FgksTfSiMUYZglrqALKTd3DFy9w18VHputO"
      ],
      "price": 240,
      "costPrice": 150,
      "priceNeedsReview": false,
      "weight": 0.5,
      "height": 15,
      "width": 20,
      "depth": 15,
      "availability": 3,
      "rating": 4.5,
      "numReviews": 10,
      "isFirstPage": true,
      "isUnique": false,
      "isActive": true,
      "banner": "/images/banner-1.jpg",
      "tags": [
        "insect",
        "bee",
        "animal"
      ],
      "crafterUserEmail": "charles@streetcraft.co.za"
    },
    {
      "name": "Zebra-small",
      "slug": "zebra-small",
      "category": "Beadwork",
      "description": "A cute zebra, and can be recreated for sure",
      "images": [
        "https://utfs.io/f/LQrirZFCBqETH6UTW0Dknrx1fWv96j7YgHCTyRscBFKIVNzG"
      ],
      "price": 150,
      "costPrice": 50,
      "priceNeedsReview": false,
      "weight": 0.5,
      "height": 20,
      "width": 10,
      "depth": 15,
      "availability": 3,
      "rating": 4.9,
      "numReviews": 3,
      "isFirstPage": true,
      "isUnique": false,
      "isActive": true,
      "banner": null,
      "tags": [
        "zebra",
        "antelope",
        "animal"
      ],
      "crafterUserEmail": "charles@streetcraft.co.za"
    },
    {
      "name": "Fish medium",
      "slug": "fish-medium",
      "category": "Beadwork",
      "description": "A great work of art",
      "images": [
        "https://utfs.io/f/LQrirZFCBqETHfyPsbDknrx1fWv96j7YgHCTyRscBFKIVNzG"
      ],
      "price": 300,
      "costPrice": 200,
      "priceNeedsReview": false,
      "weight": 1,
      "height": 25,
      "width": 6,
      "depth": 30,
      "availability": 1,
      "rating": 0,
      "numReviews": 0,
      "isFirstPage": true,
      "isUnique": true,
      "isActive": true,
      "banner": null,
      "tags": [
        "fish",
        "animal",
        "aquatic"
      ],
      "crafterUserEmail": "charles@streetcraft.co.za"
    },
    {
      "name": "Sheep small",
      "slug": "sheep-small",
      "category": "Beadwork",
      "description": "Cute sheep",
      "images": [
        "https://utfs.io/f/LQrirZFCBqETAxXnRgpyWekQ5RtHTEwaU728ONmhcplj9Cn0"
      ],
      "price": 500,
      "costPrice": 340,
      "priceNeedsReview": false,
      "weight": 1,
      "height": 12,
      "width": 10,
      "depth": 18,
      "availability": 1,
      "rating": 0,
      "numReviews": 0,
      "isFirstPage": true,
      "isUnique": true,
      "isActive": true,
      "banner": null,
      "tags": [
        "animal",
        "sheep",
        "farm"
      ],
      "crafterUserEmail": "charles@streetcraft.co.za"
    }
  ]
};

export default sampleData;
