// Exports the current dev database into db/sample-data.ts so it can be
// reused as seed data. Run with:  npm run seed:export
//
// Relationships are captured deterministically by email:
//   - Crafter -> User via `userEmail`
//   - Product -> Crafter via `crafterUserEmail` (the crafter's linked user email)
//
// Passwords are stored as their existing bcrypt hashes (or null), so seeded
// logins behave identically to the snapshot.

import { PrismaClient } from '@prisma/client';
import { writeFileSync } from 'fs';
import path from 'path';

const prisma = new PrismaClient();

async function main() {
  const [users, categories, crafters, products] = await Promise.all([
    prisma.user.findMany({ orderBy: { createdAt: 'asc' } }),
    prisma.category.findMany({ orderBy: { name: 'asc' } }),
    prisma.crafter.findMany({ include: { user: true }, orderBy: { createdAt: 'asc' } }),
    prisma.product.findMany({
      include: { crafter: { include: { user: true } } },
      orderBy: { createdAt: 'asc' },
    }),
  ]);

  const data = {
    users: users.map((u) => ({
      name: u.name,
      email: u.email,
      password: u.password,
      role: u.role,
    })),
    categories: categories.map((c) => ({
      name: c.name,
      description: c.description,
      isActive: c.isActive,
    })),
    crafters: crafters.map((c) => ({
      userEmail: c.user?.email ?? null,
      businessName: c.businessName,
      description: c.description,
      location: c.location,
      mobile: c.mobile,
      category: c.category,
      whatsappNumber: c.whatsappNumber,
      city: c.city,
      province: c.province,
      profileImage: c.profileImage,
      workSamples: c.workSamples,
      status: c.status,
      identityVerified: c.identityVerified,
      isActive: c.isActive,
    })),
    products: products.map((p) => ({
      name: p.name,
      slug: p.slug,
      category: p.category,
      description: p.description,
      images: p.images,
      price: p.price,
      costPrice: p.costPrice,
      priceNeedsReview: p.priceNeedsReview,
      weight: p.weight,
      height: p.height,
      width: p.width,
      depth: p.depth,
      availability: p.availability,
      rating: p.rating,
      numReviews: p.numReviews,
      isFirstPage: p.isFirstPage,
      isUnique: p.isUnique,
      isActive: p.isActive,
      banner: p.banner,
      tags: p.tags,
      crafterUserEmail: p.crafter?.user?.email ?? null,
    })),
  };

  const fileContent =
    `// AUTO-GENERATED by scripts/export-seed.ts on ${new Date().toISOString()}\n` +
    `// Snapshot of the dev database used as seed data.\n` +
    `// Regenerate after changing data in the DB with:  npm run seed:export\n` +
    `// Then re-seed with:  npm run seed\n\n` +
    `const sampleData = ${JSON.stringify(data, null, 2)};\n\n` +
    `export default sampleData;\n`;

  const outPath = path.join(process.cwd(), 'db', 'sample-data.ts');
  writeFileSync(outPath, fileContent, 'utf8');

  console.log(
    `Exported ${data.users.length} users, ${data.categories.length} categories, ` +
      `${data.crafters.length} crafters, ${data.products.length} products -> db/sample-data.ts`
  );
}

main()
  .catch((e) => {
    console.error('Export failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
